#!/bin/bash

# this assumes "/mnt/mega/" is a network share

testfile=/mnt/mega/.immaraid # dumb but quick way to check if the share is mounted
remote_dumpdir=/mnt/mega/downloads/torrents/ # where the torrent manager looks for torrents to load
local_dumpdir=/home/hax/.torrents # a place to declutter your download directory into
downloaddir=/home/hax # where your browser saves downloads by default

mvtorrents(){
	srcdir=$1
	destdir=$2
	if [[ `find $srcdir -maxdepth 1 -iregex '.*([0-9]*)\.torrent' | wc -l` -gt 0 ]] ;then
		dups=`find $srcdir -maxdepth 1 -iregex '.*([0-9]*)\.torrent'`
		for i in ${dups// /;;;;;} ;do
			rm -rf ${i//;;;;;/ }
		done
	fi
	if [[ `find $srcdir -maxdepth 1 -iname '*.torrent' | wc -l` -gt 0 ]] ;then
		mv $srcdir/*.torrent $destdir/
	fi
}

if [ -f $testfile ] ;then
	mvtorrents $downloaddir $remote_dumpdir
	mvtorrents $local_dumpdir $remote_dumpdir
else
	mvtorrents $downloaddir $local_dumpdir
fi
