#!/bin/bash
# Copyright 2014 haxwithaxe
# License: CC0

# Launch firefox with a new separate profile in "private" mode.

PROFILE_TEMPLATE=$HOME/.local/share/firefox-anon/profile_template

profile_dir=$(mktemp -d /tmp/firefox-anon.XXX)
app_exec="firefox"

# To create a profile comment this line out and ...
cp -r $PROFILE_TEMPLATE/* $profile_dir
# uncomment this one ...
#$app_exec --CreateProfile "$(basename $profile_dir) $profile_dir"
# Then run this script once.
# Make changes to the config.
# Copy the profile directory it created to $PROFILE_TEMPLATE.
# Exit firefox and reverse the changes to this script.
$app_exec --profile $profile_dir \
	--new-instance \
	--private \
	$*

echo "Shredding $profile_dir ..."
# Scrub the temporary profile files
# If this fails the profile directory will still be removed
find "$profile_dir" -type f -exec shred -ux {} \;
# Remove the profile directory
rm -rf "$profile_dir"
echo "Done."
