#!/bin/bash
# Copyright 2014 haxwithaxe
# License: CC0

# No, no plugins. Run a profile with no plugins.

today=`date --date='Today 00:00:00' +%s`
profile="junk"
app_exec="firefox"
app="$app_exec-$profile"
# arguments for the initial launching of this profile of firefox
first_args="-P $profile \
	-new-instance \
	-safe-mode \
	$*"
# arguments for subsequent launches
subseq_args="-P $profile -safe-mode $*"

# getto pid file
pid_file=/tmp/run/$app/pid
if ! [ -d `dirname $pid_file` ] ;then
	mkdir -p `dirname $pid_file`
fi
touch $pid_file

# is this profile already running?
is_running(){
	running=1
	pid_list=''
	while read p ;do
		if ( ps $p | grep -qo $p ) ;then
			running=0
			pid_list=${pid_list}\n$p
		fi
	done < $pid_file
	echo -ne $pid_list > $pid_file
	return $running
}

if is_running ;then
	echo already running
	$app_exec $subseq_args &
	pid=$!
	echo $pid >> $pid_file
else
	echo first instance
	$app_exec $first_args &
	pid=$!
	echo $pid >> $pid_file
fi
