#!/bin/bash
# Copyright 2014 haxwithaxe
# License: CC0

# Launch firefox under the default profile

called_as=$(basenam $0 sh)
today=`date --date='Today 00:00:00' +%s`
profile="default"
app_exec="firefox"
app="$app_exec-$profile"
first_args="-P $profile \
	-new-instance \
	$*"
subseq_args="-P $profile $*"
pid_file=/tmp/run/$app/pid
if ! [ -d `dirname $pid_file` ] ;then
	mkdir -p `dirname $pid_file`
fi
touch $pid_file

is_running(){
	running=1
	pid_list=''
	while read p ;do
		if ( ps $p | grep -qo $p ) ;then
			running=0
			pid_list=${pid_list}\n$p
		fi
	done < $pid_file
	echo -ne $pid_list > $pid_file
	return $running
}

set_name(){
	xprop -id $1 -set name "${called_as}-$2"
}

set_window_name_from_pid(){
	wins=`xwininfo -root -children 2>/dev/null | grep -i $app_name | grep -vi popup | sed 's/^[[:space:]]\+//g;s/'`
	for w in $wins ;do
		wpid=`xprop -id $w _NET_WM_PID | awk '{print $3}'`
		if [ "$wid" -eq "$w" ] ;then
			set_name $wid $pid
			return 0
		fi
	done
}

if is_running ;then
	echo already running
	$app_exec $subseq_args &
	pid=$!
	echo $pid >> $pid_file
	set_window_name_from_pid $pid
else
	echo first instance
	$app_exec $first_args &
	pid=$!
	echo $pid >> $pid_file
fi
