#!/bin/sh
# jackd-audioadapters - add nonprimary sound cards to jackd


# usb sound card to radio
jack_load -i "-d hw:C1100" ft857 audioadapter

# onboard soundcard which is broken but still kinda works
jack_load -i "-d hw:Intel" onboard audioadapter

cat - &> /dev/null
