#!/bin/bash

USAGE="$0 <input file> <output file>"
STYLESHEET=/tmp/prettyxml.xsl

# Create prettyxml.xsl
cat - > $STYLESHEET <<EOF
<?xml version="1.0" encoding="utf-8" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="xml" encoding="UTF-8" omit-xml-declaration="yes"/>
</xsl:stylesheet>
EOF

SRC=$1
DEST=$2

if [[ -z $SRC ]];then
	echo $USAGE
	exit 1
fi
if [[ -n $DEST ]]; then
	DEST="-o $DEST"
fi

xsltproc $DEST $STYLESHEET $SRC
echo "done"

rm $STYLESHEET

exit 0
