#!/usr/bin/env python3

import argparse
import sys

from lxml import etree


def main():
	parser = argparse.ArgumentParser()
	parser.add_argument('-o', '--output', default=None, help='Ouput file. Defaults to stdout.')
	parser.add_argument('input', nargs='?', help='Input filename. Defaults to stdin.')
	args = parser.parse_args()
	infile = sys.stdin if args.input in (None, '-') else open(args.input, 'r')
	outfile = '/dev/stdout' if args.output in (None, '-') else args.output
	etree.parse(infile).write(outfile, pretty_print=True)

if __name__ == '__main__':
	try:
		main()
	except etree.Error as err:
		print(err, file=sys.stderr)
	except KeyboardInterrupt:
		pass
