#!/usr/bin/env python

import argparse
import datetime
import time

def main():
	parser = argparse.ArgumentParser()
	parser.add_argument("-t","--time", type=float)
	parser.add_argument("-s","--strtime")
	parser.add_argument("-f","--format", default='%s')
	args = parser.parse_args()
	if args.strtime:
		return time.mktime(time.strptime(args.strtime, args.format))
	elif args.time:
		return datetime.datetime.fromtimestamp(args.time).strftime(args.format)
	else:
		return parser.usage()

if __name__ == '__main__':
	try:
		print(main())
	except ValueError as e:
		print(e)
