#!/bin/bash

url=$1
cachefile="/var/cache/ipv6addr.cache"

if [ -f $cachefile ] ;then
	IPCACHE=`cat ${cachefile}`
else
	IPCACHE=''
fi

IPNOW=`ifconfig | grep Global | cut -d' ' -f13 | cut -d'/' -f1`

if [[ $IPCACHE != $IPNOW ]];then
        wget -q "http://freedns.afraid.org/dynamic/update.php?${url}&address=${IPNOW}" -O - 2>&1 > /dev/null
        echo $IPNOW > $cachefile
fi
